# ----------
# stage 01
# build
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements-train.txt .
RUN pip install --no-cache-dir -r requirements-train.txt
# ----------
# stage 02
FROM python:3.11-slim
WORKDIR /app

# /usr/local/lib/python3.11/site-packages/
#    ├── numpy/
#    ├── pandas/
#    ├── scikit_learn/
#    └── ...

# COPY A B (voce esta copiando o conteudo de A para B)
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY src/ src/
COPY data/ data/

ENV DB_PATH="data/heat_exchanger.db"\
    MODEL_PATH="artifacts/heat_efficiency_model.pkl"


# para o artefato persistir
# docker run -v $(pwd)/artifacts:/app/artifacts docker-ml-projeto-train
CMD ["python", "src/train.py"]
# ----------