# ----------
# stage 01
# build
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements-inference.txt .
RUN pip install --no-cache-dir -r requirements-inference.txt
# ----------
# stage 02
FROM python:3.11-slim
WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY src/ src/

ENV DB_PATH="data/heat_exchanger.db"\
    MODEL_PATH="artifacts/heat_efficiency_model.pkl"


# para o artefato persistir
# docker run -v $(pwd)/artifacts:/app/artifacts docker-ml-projeto-inference python src/inference.py --efficiency 300

CMD ["python", "src/inference.py"]